from Card import Card

class Cards:
    def __init__(self):
        self.cards_list = [
            Card('2', 2, 'pik'),
            Card('3', 3, 'pik'),
            Card('4', 4, 'pik'),
            Card('5', 5, 'pik'),
            Card('6', 6, 'pik'),
            Card('7', 7, 'pik'),
            Card('8', 8, 'pik'),
            Card('9', 9, 'pik'),
            Card('10', 10, 'pik'),
            Card('Walet', 11, 'pik'),
            Card('Dama', 12, 'pik'),
            Card('Król', 13, 'pik'),
            Card('AS', 14, 'pik'),
            Card('2', 2, 'kier'),
            Card('3', 3, 'kier'),
            Card('4', 4, 'kier'),
            Card('5', 5, 'kier'),
            Card('6', 6, 'kier'),
            Card('7', 7, 'kier'),
            Card('8', 8, 'kier'),
            Card('9', 9, 'kier'),
            Card('10', 10, 'kier'),
            Card('Walet', 11, 'kier'),
            Card('Dama', 12, 'kier'),
            Card('Król', 13, 'kier'),
            Card('AS', 14, 'kier'),
            Card('2', 2, 'trefl'),
            Card('3', 3, 'trefl'),
            Card('4', 4, 'trefl'),
            Card('5', 5, 'trefl'),
            Card('6', 6, 'trefl'),
            Card('7', 7, 'trefl'),
            Card('8', 8, 'trefl'),
            Card('9', 9, 'trefl'),
            Card('10', 10, 'trefl'),
            Card('Walet', 11, 'trefl'),
            Card('Dama', 12, 'trefl'),
            Card('Król', 13, 'trefl'),
            Card('AS', 14, 'trefl'),
            Card('2', 2, 'karo'),
            Card('3', 3, 'karo'),
            Card('4', 4, 'karo'),
            Card('5', 5, 'karo'),
            Card('6', 6, 'karo'),
            Card('7', 7, 'karo'),
            Card('8', 8, 'karo'),
            Card('9', 9, 'karo'),
            Card('10', 10, 'karo'),
            Card('Walet', 11, 'karo'),
            Card('Dama', 12, 'karo'),
            Card('Król', 13, 'karo'),
            Card('AS', 14, 'karo'),
        ]